version: 1.0.{build}
services: mssql2012sp1
before_build:
- sqlcmd -S ".\SQL2012SP1" -U sa -P Password12! -i "%APPVEYOR_BUILD_FOLDER%\Create_Test_Database_Schema.sql"
build:
  project: Proteus.Domain.build.xml
  verbosity: minimal